name: Tests
on: [push, pull_request, workflow_dispatch]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: FedericoCarboni/setup-ffmpeg@v3        
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -U pytest
          pip install .[usm]
      - name: Run tests
        run: |
          pytest -v -s